---
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch-command:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            schedule-test-run
            cancel-tests
            print-result
            help
          issue-type: pull-request
          permission: none
